- name: get current sites-enabled
  find:
    paths: "/etc/nginx/sites-enabled"
  register: sites_enabled

- name: delete all current sites-enabled
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ sites_enabled.files }}"

- name: put maintenance page to sites-enabled
  file:
    src: "/etc/nginx/sites-available/maintenance"
    dest: "/etc/nginx/sites-enabled/maintenance"
    state: link
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644

- name: restart nginx
  service:
    name: nginx
    state: reloaded
