user: ubuntu
group: users
nvm:
  dir: /home/{{ user }}/.nvm
  profile: /home/{{ user }}/.bashrc
  version: v0.33.2
  node_version: 6.9.1
start_port: 3000
total_instances: 2
instance_location: /instances/v{{ website_version }}
